# use a imagem oficial do Nginx com a imagem base
FROM nginx:latest

# Copie o arquivo de configuracao personalizado para dentro do container
COPY index.html /usr/share/nginx/html/index.html

# exponha a porta 80 para permitir o acesso ao servidor web
EXPOSE 80